 USE DATABASE GFR_LOAD_DB;
 USE SCHEMA GIT_INTEGRATION;

USE ROLE GFR_DEV_TEAM;

show schemas;
show integrations;
show secrets;
show GIT REPOSITORIES;
 
  // TO FETCH LATEST FILES
  // EXECUTE:
ALTER GIT REPOSITORY GFR_DWH_PROJECT FETCH;

  // TO SHOW GIT BRANCHES
  // EXECUTE:
SHOW GIT BRANCHES IN GFR_DWH_PROJECT;


  // TO LIST FILES IN THE REPO MAIN BRANCH
  // EXECUTE:
  LS @GFR_DWH_PROJECT/branches/main;
