USE WAREHOUSE GLOBAL_FASHION_RETAIL_LOAD_WH_XSMALL;
USE DATABASE GFR_LOAD_DB;
USE SCHEMA EXCHANGERATE;

-- Create Network Rule
CREATE OR REPLACE NETWORK RULE GFR_API_INTEGRATION_EXCHANGERATE
    MODE = EGRESS
    TYPE = HOST_PORT
    VALUE_LIST = ('open.er-api.com:443');


CREATE OR REPLACE SECRET GFR_EXCHANGERATE_SECRET
    TYPE = GENERIC_STRING
    SECRET_STRING = '<api-key>';

CREATE  EXTERNAL ACCESS INTEGRATION GFR_ACCESS_EXCHANGERATE
  ALLOWED_NETWORK_RULES = (GFR_API_INTEGRATION_EXCHANGERATE)
  ALLOWED_AUTHENTICATION_SECRETS = (GFR_EXCHANGERATE_SECRET)
  ENABLED = TRUE;


