USE WAREHOUSE GLOBAL_FASHION_RETAIL_LOAD_WH_XSMALL;
USE DATABASE GFR_LOAD_DB;
USE SCHEMA ORCHESTRATION;

ALTER TASK COPY_STORES_TASKS ADD AFTER GFR_PIPELINES_START_TASK;
ALTER TASK COPY_TRANSACTIONS_TASKS ADD AFTER GFR_PIPELINES_START_TASK; 

-- run tasks
ALTER TASK GFR_PIPELINES_END_TASK RESUME;
-- ALTER TASK MERGE_STORES_STG_TASK RESUME;
-- ALTER TASK MERGE_TRANSACTION_STG_TASK RESUME;
ALTER TASK COPY_STORES_TASKS RESUME;
ALTER TASK COPY_TRANSACTIONS_TASKS RESUME;
ALTER TASK GFR_PIPELINES_START_TASK RESUME;




-- snow sql -q "ALTER GIT REPOSITORY GFR_LOAD_DB.GIT_INTEGRATION.GFR_DWH_PROJECT FETCH"
-- snow sql -q "EXECUTE IMMEDIATE FROM @GFR_LOAD_DB.GIT_INTEGRATION.GFR_DWH_PROJECT/branches/main/scripts/deployment/resume_tasks.sql" --warehouse "GLOBAL_FASHION_RETAIL_LOAD_WH_XSMALL";